### ISSUE TITLE
No Instructions on how to use

### ISSUE THREAD

**Issue by lunarcloud** [thimenesup/GodotNFC#1]
I have no idea what to do with this java file to implement the feature in a blank godot template.

**Comment by thimenesup** [comment]
[The plugin was written for the old 2.1 version, I assumed that for anybody that read the instructions, would already have it figured since its pretty straightforward to implement (basically drag said files in the module folder, thats it.) ](https://docs.godotengine.org/en/2.1/development/cpp/creating_android_modules.html)

[Last commit updated it for the 3.2 version, so you will need to follow these steps instead](https://docs.godotengine.org/en/latest/tutorials/platform/android/android_plugin.html)
